- name: install monitoring stack
  hosts: localhost
  become: yes
  roles:
   - prometheus
   - alertmanager
   - grafana
- name: install node-exporter
  hosts: tag_Name_webapp_poc
  become: yes
  roles:
   - node-exporter