---
serviceName: "alertmanager"
userId: "alertmanager"
groupId: "alertmanager"
exec_command: "/usr/local/bin/alertmanager --config.file=/etc/alertmanager/alertmanager.yml --storage.path=/"
version: "0.25.0"
