---
- name: download and unzip prometheus if not exist
  unarchive:
    src: "https://github.com/prometheus/prometheus/releases/download/v{{ prometheus_version }}/prometheus-{{ prometheus_version }}.linux-amd64.tar.gz"
    dest: /tmp/
    remote_src: yes
    validate_certs: no

- name: copy binaries to destination
  copy:
   src: /tmp/prometheus-{{ prometheus_version }}.linux-amd64/ 
   dest: "{{ prometheus_bin }}"
   owner: "{{ prometheus_user }}"
   group: "{{ prometheus_group }}"
   mode: 0755
   remote_src: yes  
  
- name: copy files to destination
  copy:
   src: /tmp/prometheus-{{ prometheus_version }}.linux-amd64/                  
   dest: "{{ prometheus_dir_conf }}"

- name: clean
  file:
    path: /tmp/prometheus-{{ prometheus_version }}.linux-amd64/
    state: absent

- name: creating prometheus user
  user:
    name: "{{ prometheus_user }}"
    append: true
    shell: /usr/sbin/nologin
    system: true
    create_home: false  

- name: create prometheus config dir
  file:
    path: /etc/prometheus
    state: directory
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_group }}"

- name: prometheus configuration file
  template:
    src: prometheus.yml.j2
    dest: "{{ prometheus_dir_conf }}/prometheus.yml"
    mode: 0755
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_group }}"
  notify:
    - reload_prometheus 

- name: install service
  template:
    src: templates/prometheus.service.j2
    dest: /etc/systemd/system/prometheus.service
    owner: root
    group: root
    mode: 0755
  notify: 
    - restart_prometheus

- name: service always started
  systemd:
    name: prometheus
    state: started
    enabled: yes
