prometheus_version: "2.45.0"
prometheus_user: "prometheus"
prometheus_group: "{{ prometheus_user}}"
prometheus_bin: "/usr/local/bin/"
prometheus_dir_conf: "/etc/prometheus/"
prometheus_retention_time: "365d"
prometheus_scrape_interval: "30s"
prometheus_node_exporter: true
prometheus_node_exporter_group: "all"
prometheus_env: "poc"
prometheus_var_config:
  global:
    scrape_interval: "{{ prometheus_scrape_interval }}"
    evaluation_interval: 5s
    external_labels:
      env: '{{ prometheus_env }}'
  scrape_configs:
    - job_name: prometheus
      scrape_interval: 5m
      static_configs:
        - targets: ['{{ inventory_hostname }}:9090']
